### ISSUE TITLE
Short Dump Downloading Variant

### ISSUE THREAD

**Issue by habrahams** [larshp/upDOWNci#17]
Hi,
I get short dump when downloading a test variant in test mode. (Note quite sure if it is because of the fact that I changed some of the check's priority from Warning to Error).
This is the first time that I'm trying to download a check variant.
![image](https://user-images.githubusercontent.com/16045067/89508677-8c948580-d7ce-11ea-84cc-6f7c07be9366.png)
![image](https://user-images.githubusercontent.com/16045067/89508730-9a4a0b00-d7ce-11ea-9164-6027d1740b56.png)

SAP_BASIS	750	0006	SAPK-75006INSAPBASIS	SAP Basis Component

**Comment by larshp** [comment]
what is the value of `iv_class` ? the upload download is quite a hack, and some classes are special, so try excluding it if possible

**Comment by habrahams** [comment]
Thanks Lars, the class is CL_CI_TEST_CRITICAL_STATEMENTS.

**Comment by larshp** [comment]
okay, cool, then we can change ZCL_AOC_CHECK_100 so it works with the upload download, but requires some debugging

**Comment by habrahams** [comment]
If I get a chance a bit later I'll debug and get back to you if I find something.....

**Comment by larshp** [comment]
I'm fixing it

**Comment by larshp** [comment]
try again, 

https://github.com/larshp/upDOWNci/commit/cd6b063d4c415dd94bc3c3ec12fd71f9de02501a

https://github.com/larshp/abapOpenChecks/commit/5217eacbaa95f003e442ce71c59dc03155a171b0

**Comment by habrahams** [comment]
Thanks Lars, the issue is resolved.
