### ISSUE TITLE
Is not supporting checks from "code pal for ABAP"

### ISSUE THREAD

**Issue by larsip** [larshp/upDOWNci#19]
Have exported a ATC variant containing "code pal for ABAP (open source plugin)" - "CALL METHOD Usage". Program ZUPDOWNCI is dumping because the tool is not supporting that the test class is not implementing method PUT_ATTRIBUTES directly in the class. Class Y_CHECK_CALL_METHOD_USAGE method PUT_ATTRIBUTES is inherit from superclass Y_CHECK_BASE.

**Comment by larshp** [comment]
hmm, yea, thanks

probably need some workaround, pull requests welcome

**Comment by larsip** [comment]
I have investigated what is wrong and can see that it is not the inherence that is the issue.
The reason why it don't work for checks from "code pal for ABAP (open source plugin)", is that in method PUT_ATTRIBUTES instead for just importing data into attributes of the ATC test class, the data is imported into a structure and the structure is appended to attribute table CHECK_CONFIGURATIONS. And then the logic about generation of dynamic structures and exporting the data in the XML structure is not working.

**Comment by larshp** [comment]
closing, this is fixed in #20
