### ISSUE TITLE
remove slash from default filename

### ISSUE THREAD

**Issue by buettnerjulian** [larshp/upDOWNci#21]
Hey Lars,

maybe you can add this line to your code, to fix the issue if some uses variants with slashes.
![image](https://user-images.githubusercontent.com/53438585/140037283-13b95f9f-978a-4dfb-9dca-4da27a0b2fe0.png)

Best regards,
Julian

**Comment by larshp** [comment]
yea, thanks, can you help creating a PR for the change?

**Comment by buettnerjulian** [comment]
PR is open.
