### ISSUE TITLE
Exception CL_CI_TEST_PRETTY_PRINT

### ISSUE THREAD

**Issue by JmGerardLactalis** [larshp/upDOWNci#33]
Hello,

I have an exception with "CL_CI_TEST_PRETTY_PRINT" but i don't know why, could you help me ? 

![2024-10-30_21h15_52](https://github.com/user-attachments/assets/29ed1552-d7ab-44a5-bfbf-bf5168f050c2)

**Comment by ConjuringCoffee** [comment]
Probably the same issue as in: https://github.com/larshp/upDOWNci/issues/23

**Comment by JmGerardLactalis** [comment]
Is a patch available?

**Comment by ConjuringCoffee** [comment]
The other issue is still open, so no. You can close this one if it is a duplicate
